### ISSUE TITLE
Add `disable` option

### ISSUE THREAD

**Issue by agustinl** [agustinl/svelte-tags-input#23]
- [x] Add `disable` option
- [x] Add the css according to the disable option

**Comment by agustinl** [comment]
```css
/* svelte-tags-input disabled */
.svelte-tags-input-layout.sti-layout-disable,
.svelte-tags-input:disabled {
    background: #EAEAEA;
    cursor: not-allowed;
}

.svelte-tags-input-layout.sti-layout-disable:hover,
.svelte-tags-input-layout.sti-layout-disable:focus {
    border-color:#CCC;
}

.svelte-tags-input-layout.sti-layout-disable .svelte-tags-input-tag {
    background: #AEAEAE;
}

.svelte-tags-input-layout.sti-layout-disable .svelte-tags-input-tag-remove {
    cursor: not-allowed;
}
```
