### ISSUE TITLE
Feature request - add custom class

### ISSUE THREAD

**Issue by mylastore** [agustinl/svelte-tags-input#6]
I can't override the CSS would be nice to add a custom class on the options for example
```
       <Tags 
              on:tags={handleTags}
              addKeys={[9]}
              maxTags={5}
              onlyUnique={true}
              placeholder={"Click tab to enter product tags"}
              className={"my-custom-class"}
```

**Comment by mylastore** [comment]
By the way this is Awesome!!!! Thank You,  I see that event by adding a custom CSS class would not help that much since the parent DIV is handling most of the CSS to mimic the input.

**Comment by agustinl** [comment]
Hi Oscar! how are you?
I ready added a little doc in the repo to override the default css.

```html
<div  class="my-custom-class"> 
    <Tags /> 
</div>
```

```css
<style>
.my-custom-class :global(.svelte-tags-input-tag) {
    background:blue;
}

.my-custom-class :global(.svelte-tags-input-layout) {
    background:yellow;
}
</style>
```

Could you verify if this work for you? Is working for me.

Thanks for using the component!
